# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "996d89eec2810e43f7bf857fc60fd60a"
name = "shop-ops-suite"
application_url = "https://huong.fwurl.com"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "customers/update" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_customers,write_orders,write_inventory"

[auth]
redirect_urls = [
  "https://huong.fwurl.com/offline/auth/callback",
  "https://huong.fwurl.com/online/auth/callback",
  "https://huong.fwurl.com/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
